=== xc-lord/lord-all/lord-biz/src/main/resources/page_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.xiaocheng.xyz"
        xmlns="http://www.xiaocheng.xyz"
        elementFormDefault="qualified"
        >

    <!-- 简易元素定义 -->
    <xs:element name="template_num" type="xs:int"></xs:element><!-- 创建的模板个数 -->
    <xs:element name="page_name" type="xs:string"></xs:element><!-- 页面名称 -->
    <xs:element name="page_code" type="xs:string"></xs:element><!-- 页面关键字 -->
    <xs:element name="keyword" type="xs:string"></xs:element><!-- 模板关键字 -->
    <xs:element name="name" type="xs:string"></xs:element><!-- 模板名称 -->
    <xs:element name="intro" type="xs:string"></xs:element><!-- 配置说明 -->
    <xs:element name="type"><!-- 模板类型 -->
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="模板"></xs:enumeration>
                <xs:enumeration value="图片链接"></xs:enumeration>
                <xs:enumeration value="文字链接"></xs:enumeration>
                <xs:enumeration value="大文本"></xs:enumeration>
                <xs:enumeration value="文章"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="count" type="xs:int"></xs:element><!-- 模板内容的元素个数 -->
    <xs:element name="choose" type="xs:boolean" default="false"></xs:element><!-- 查询模板的子模板时是否需要根据配置进行筛选 -->
    <xs:element name="isDefault" type="xs:boolean" default="true"></xs:element><!-- 筛选子模板时，该模板是否默认的选项 -->

    <!-- 复合元素定义 -->
    <xs:element name="template">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"></xs:element>
                <xs:element ref="keyword"></xs:element>
                <xs:element ref="type"></xs:element>
                <xs:element ref="intro" minOccurs="0"></xs:element>
                <xs:element ref="template_num" minOccurs="0"></xs:element>
                <xs:element ref="count" minOccurs="0"></xs:element>
                <xs:element ref="choose" minOccurs="0"></xs:element>
                <xs:element ref="isDefault" minOccurs="0"></xs:element>
                <xs:element name="children" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="template" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="page_template">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="page_name" type="xs:string"></xs:element>
                <xs:element name="page_code" type="xs:string"></xs:element>
                <xs:element ref="choose" minOccurs="0"></xs:element>
                <xs:element name="children">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="template" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== xc-lord/lord-all/lord-biz/src/main/resources/page/eduH5CommonData.xml
<?xml version="1.0" encoding="UTF-8"?>
<page_template xmlns="http://www.xiaocheng.xyz"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.xiaocheng.xyz  ../page_template.xsd">
    <page_name>H5公共页头页尾</page_name>
    <page_code>eduH5CommonData</page_code>
    <children>
        <template>
            <name>头部LOGO</name>
            <keyword>headerLogo</keyword>
            <type>图片链接</type>
            <count>1</count>
        </template>
        <template>
            <name>头部导航</name>
            <keyword>headerLink</keyword>
            <type>文字链接</type>
            <count>6</count>
        </template>
        <template>
            <name>底部链接</name>
            <keyword>footerLink</keyword>
            <type>文字链接</type>
            <count>3</count>
        </template>
        <template>
            <name>二维码</name>
            <keyword>QRCode</keyword>
            <type>图片链接</type>
            <count>1</count>
        </template>
        <template>
            <name>版权信息</name>
            <keyword>copyright</keyword>
            <type>文字链接</type>
            <count>1</count>
        </template>
        <template>
            <name>TDK</name>
            <keyword>TDK</keyword>
            <type>文字链接</type>
            <count>1</count>
        </template>
    </children>
</page_template>

=== xc-lord/lord-all/lord-biz/src/main/resources/page/eduPCIndex.xml
<?xml version="1.0" encoding="UTF-8"?>
<page_template xmlns="http://www.xiaocheng.xyz"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.xiaocheng.xyz  ../page_template.xsd">
    <page_name>PC首页</page_name>
    <page_code>eduPCIndex</page_code>
    <children>
        <template>
            <name>焦点图</name>
            <keyword>JiaoDianTu</keyword>
            <type>图片链接</type>
            <count>4</count>
        </template>
        <template>
            <name>分类</name>
            <keyword>category</keyword>
            <type>模板</type>
            <template_num>4</template_num>
            <children>
                <template>
                    <name>标题</name>
                    <keyword>title</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
                <template>
                    <name>链接</name>
                    <keyword>link</keyword>
                    <type>文字链接</type>
                    <count>15</count>
                </template>
            </children>
        </template>
        <template>
            <name>推荐学校</name>
            <keyword>XueXiao</keyword>
            <type>图片链接</type>
            <count>8</count>
        </template>
        <template>
            <name>推荐专业</name>
            <keyword>ZhuanYe</keyword>
            <type>图片链接</type>
            <count>4</count>
        </template>
        <template>
            <name>热门系别</name>
            <keyword>XiBie</keyword>
            <type>图片链接</type>
            <count>4</count>
        </template>
        <template>
            <name>报考指南</name>
            <keyword>BaoKao</keyword>
            <type>图片链接</type>
            <count>4</count>
        </template>
    </children>
</page_template>

=== xc-lord/lord-all/lord-biz/src/main/resources/page/eduCommonData.xml
<?xml version="1.0" encoding="UTF-8"?>
<page_template xmlns="http://www.xiaocheng.xyz"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.xiaocheng.xyz  ../page_template.xsd">
    <page_name>公共页头页尾</page_name>
    <page_code>eduCommonData</page_code>
    <children>
        <template>
            <name>头部LOGO</name>
            <keyword>headerLogo</keyword>
            <type>图片链接</type>
            <count>1</count>
        </template>
        <template>
            <name>头部导航</name>
            <keyword>headerLink</keyword>
            <type>文字链接</type>
            <count>6</count>
        </template>
        <template>
            <name>友情链接</name>
            <keyword>friendlyLink</keyword>
            <type>文字链接</type>
            <count>10</count>
        </template>
        <template>
            <name>底部LOGO</name>
            <keyword>footerLogo</keyword>
            <type>图片链接</type>
            <count>1</count>
        </template>
        <template>
            <name>二维码</name>
            <keyword>QRCode</keyword>
            <type>图片链接</type>
            <count>1</count>
        </template>
        <template>
            <name>版权信息</name>
            <keyword>copyright</keyword>
            <type>文字链接</type>
            <count>1</count>
        </template>
        <template>
            <name>底部菜单</name>
            <keyword>footer</keyword>
            <type>模板</type>
            <template_num>4</template_num>
            <children>
                <template>
                    <name>标题</name>
                    <keyword>title</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
                <template>
                    <name>链接</name>
                    <keyword>link</keyword>
                    <type>文字链接</type>
                    <count>4</count>
                </template>
            </children>
        </template>
    </children>
</page_template>

=== xc-lord/lord-all/lord-biz/src/main/resources/page/Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<page_template xmlns="http://www.xiaocheng.xyz"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.xiaocheng.xyz  ../page_template.xsd">
    <page_name>H5首页</page_name>
    <page_code>WapIndex</page_code>
    <children>
        <template>
            <name>焦点图</name>
            <keyword>JiaoDianTu</keyword>
            <type>图片链接</type>
            <count>4</count>
        </template>
        <template>
            <name>入口图标</name>
            <keyword>RuKouTuBiao</keyword>
            <type>图片链接</type>
            <intro>名称为商品名称，标题为新品标签，子标题为用户评论，扩展属性为商品标签</intro>
            <count>4</count>
        </template>
        <template>
            <name>活动</name>
            <keyword>HuoDong</keyword>
            <type>模板</type>
            <template_num>3</template_num>
            <children>
                <template>
                    <name>标题</name>
                    <keyword>BiaoTi</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
                <template>
                    <name>轮播图</name>
                    <keyword>LunBoTu</keyword>
                    <type>图片链接</type>
                    <count>4</count>
                </template>
                <template>
                    <name>查看全部</name>
                    <keyword>QuanBu</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
            </children>
        </template>
        <template>
            <name>清单</name>
            <keyword>QingDan</keyword>
            <type>模板</type>
            <children>
                <template>
                    <name>标题</name>
                    <keyword>BiaoTi</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
                <template>
                    <name>图片</name>
                    <keyword>TuPian</keyword>
                    <type>图片链接</type>
                    <count>4</count>
                </template>
                <template>
                    <name>查看全部</name>
                    <keyword>QuanBu</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
            </children>
        </template>
        <template>
            <name>商品</name>
            <keyword>ShangPin</keyword>
            <type>模板</type>
            <children>
                <template>
                    <name>标题</name>
                    <keyword>BiaoTi</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
                <template>
                    <name>文章</name>
                    <keyword>Article</keyword>
                    <type>文章</type>
                    <count>4</count>
                </template>
                <template>
                    <name>查看全部</name>
                    <keyword>QuanBu</keyword>
                    <type>文字链接</type>
                    <count>1</count>
                </template>
            </children>
        </template>
    </children>
</page_template>
